#!/bin/bash
set -e

export GENKEY_PHASE=${GENKEY_PHASE:-false} # Disable for default.
export VAGRANT_DIR="${VAGRANT_DIR:-$(pwd)}"

# Speed up test runs by disabling slow syncs and mirror sorts
export SKIP_PORTAGE_SYNC="${SKIP_PORTAGE_SYNC:-1}"
export EQUO_MIRRORSORT="${EQUO_MIRRORSORT:-0}"

. /sbin/sark-functions.sh

if [ ! -e build.yaml ]; then
    echo "Must be run from a repository directory containing a build.yaml"
    exit 1
fi

load_env_from_yaml build.yaml

# Debug what env vars are being passed to the builder
printenv | sort

build_all ${BUILD_ARGS}
